"""Add metadata dates to base model

Revision ID: 6d7d13d0ba3d
Revises: 22a2fa1c1b6e
Create Date: 2025-01-06 21:30:23.064426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6d7d13d0ba3d"
down_revision: Union[str, None] = "22a2fa1c1b6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        schema="almbc",
    )
    op.add_column(
        "product",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_onupdate=sa.text("CURRENT_TIMESTAMP"),
        ),
        schema="almbc",
    )
    op.add_column(
        "product",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="almbc",
    )
    op.add_column(
        "technical_properties",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        schema="almbc",
    )
    op.add_column(
        "technical_properties",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_onupdate=sa.text("CURRENT_TIMESTAMP"),
        ),
        schema="almbc",
    )
    op.add_column(
        "technical_properties",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="almbc",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technical_properties", "deleted_at", schema="almbc")
    op.drop_column("technical_properties", "updated_at", schema="almbc")
    op.drop_column("technical_properties", "created_at", schema="almbc")
    op.drop_column("product", "deleted_at", schema="almbc")
    op.drop_column("product", "updated_at", schema="almbc")
    op.drop_column("product", "created_at", schema="almbc")
    # ### end Alembic commands ###
