"""Add Tag model

Revision ID: bb83d1d11682
Revises: 4aec0366cba5
Create Date: 2025-01-20 21:24:49.076107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb83d1d11682'
down_revision: Union[str, None] = '4aec0366cba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.add_column('product', sa.Column('tags', sa.JSON(), nullable=True), schema='almbc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'tags', schema='almbc')
    op.drop_table('tag', schema='almbc')
    # ### end Alembic commands ###
