"""First migration

Revision ID: 8d6806c585ac
Revises: 
Create Date: 2025-01-26 12:10:03.727253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6806c585ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('price', sa.REAL(precision=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('custom_properties', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('sku', sa.String(length=16), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='almbc'
    )
    op.create_table('user_account',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('geoip', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('address',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=64), nullable=False),
    sa.Column('email_address_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=19), nullable=False),
    sa.Column('street', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['almbc.user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('category_product_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['almbc.category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['almbc.product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id', 'id'),
    schema='almbc'
    )
    op.create_table('customer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['almbc.user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('order',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_type', sa.String(length=256), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.Double(precision=2), nullable=False),
    sa.Column('discount', sa.Double(precision=2), nullable=False),
    sa.Column('tax', sa.Double(precision=2), nullable=False),
    sa.Column('total_quantity', sa.Double(precision=2), nullable=False),
    sa.Column('products_count', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['almbc.customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='almbc'
    )
    op.create_table('order_product_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Double(precision=2), nullable=False),
    sa.Column('discount', sa.Double(precision=2), nullable=True),
    sa.Column('tax', sa.Double(precision=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['almbc.order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['almbc.product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'order_id', 'id'),
    schema='almbc'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product_association', schema='almbc')
    op.drop_table('order', schema='almbc')
    op.drop_table('customer', schema='almbc')
    op.drop_table('category_product_association', schema='almbc')
    op.drop_table('address', schema='almbc')
    op.drop_table('user_account', schema='almbc')
    op.drop_table('tag', schema='almbc')
    op.drop_table('product', schema='almbc')
    op.drop_table('category', schema='almbc')
    # ### end Alembic commands ###
