"""Link Product with Technical Properties

Revision ID: 668f6f3a880b
Revises: 742476952c37
Create Date: 2024-12-29 10:34:27.306731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "668f6f3a880b"
down_revision: Union[str, None] = "742476952c37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "technical_properties_product_id_fkey",
        "technical_properties",
        "product",
        ["product_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "technical_properties_product_id_fkey",
        "technical_properties",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
