"""First revision

Revision ID: 742476952c37
Revises: 
Create Date: 2024-12-29 08:59:54.409330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '742476952c37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('price', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_properties', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('CPU', 'RAM', 'GPU', 'Storage', 'ScreenSize', 'Resolution', 'BatteryLife', 'WaterResistance', 'Bluetooth', 'Weight', 'Battery', 'RefreshRate', 'Camera', 'Sensors', 'NoiseCancellation', 'HDR', 'Ports', 'SmartFeatures', 'OutputPower', 'ReadSpeed', 'WriteSpeed', 'Interface', 'SwitchType', 'Keycaps', 'Connectivity', 'Lighting', 'Layout', 'DPIRange', 'Buttons', name='technicalpropertyenum'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_properties')
    op.drop_table('product')
    # ### end Alembic commands ###
