CONTINENTS = [
    "Africa",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
]

AVAILABLE_PROPERTIES_CONFIGURATION = {
    "color": [
        "Red",
        "Green",
        "Blue",
        "Orange",
        "Cyan",
        "Magenta",
        "Grey",
        "Black",
        "white",
        "Brown",
        "IndianRed",
        "LightSteelBlue",
    ],
    "size": "float",
    "weight": ("float", "g"),
    "material": "string",
    "length": ("float", "cm"),
    "width": ("float", "cm"),
    "height": ("float", "cm"),
    "ram": ("choice", "Gb", [4, 8, 16, 32, 64]),
    "storage": ("choice", "Gb", [128, 256, 512]),
    "gpu": ("choice", "Gb", [4, 8, 16, 32, 64]),
    "cpu": ("float", "GHz"),
    "battery_life": ("int", "Hours"),
    "os": ["Windows", "Linux", "MacOS", "Android"],
    "connectivity": ["WiFi", "Bluetooth", "NFC", "Ethernet", "5G"],
    "ports": ["USB", "HDMI", "Thunderbolt", "Audio Jack"],
    "gender": ["F", "M"],
    "warranty": ("choice", "Months", [3, 6, 12, 24]),
    "certifications": ["Energy Star", "CE", "RoHS"],
    "extras": ["Remote Control", "Cables", "Carrying Case"],
}

CATEGORIES_LIST = [
    "Electronics",
    "Mobile Phones",
    "Laptops",
    "Tablets",
    "Smartwatches",
    "Televisions",
    "Headphones",
    "Cameras",
    "Speakers",
    "Printers",
    "Gaming Consoles",
    "Monitors",
    "Keyboards",
    "Mice",
    "Hard Drives",
    "USB Drives",
    "Power Banks",
    "Chargers",
    "Smart Home Devices",
    "Drones",
    "Home Appliances",
    "Refrigerators",
    "Washing Machines",
    "Microwaves",
    "Air Conditioners",
    "Heaters",
    "Vacuum Cleaners",
    "Coffee Makers",
    "Blenders",
    "Toasters",
    "Cookware",
    "Furniture",
    "Sofas",
    "Chairs",
    "Beds",
    "Tables",
    "Desks",
    "Wardrobes",
    "Shelves",
    "Outdoor Furniture",
    "Lighting",
    "Lamps",
    "Ceiling Lights",
    "Wall Lights",
    "Smart Lights",
    "Tools",
    "Hand Tools",
    "Power Tools",
    "Gardening Tools",
    "Outdoor Equipment",
    "Fitness Equipment",
    "Treadmills",
    "Dumbbells",
    "Exercise Bikes",
    "Yoga Mats",
    "Sports Gear",
    "Bicycles",
    "Camping Gear",
    "Tents",
    "Sleeping Bags",
    "Backpacks",
    "Clothing",
    "T-Shirts",
    "Jeans",
    "Jackets",
    "Dresses",
    "Shoes",
    "Sneakers",
    "Boots",
    "Sandals",
    "Accessories",
    "Watches",
    "Bags",
    "Belts",
    "Jewelry",
    "Hats",
    "Books",
    "Fiction",
    "Non-Fiction",
    "Comics",
    "Magazines",
    "Stationery",
    "Notebooks",
    "Pens",
    "Markers",
    "Art Supplies",
    "Toys",
    "Action Figures",
    "Puzzles",
    "Board Games",
    "Dolls",
    "Musical Instruments",
    "Guitars",
    "Pianos",
    "Drums",
    "Violins",
]
